### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by NewHospitals** [muhammad-shariq/exclusiveunlock#1]
Thanks you for the work 

I interesting the unlock service by IMEI 
Installed your script on my website my-IMEI.info. Now I have two problems 
Can’t add found 
I added my api working fine but if used the imported api service not working all time status have pending 

Thanks you advance

**Comment by muhammad-shariq** [comment]
Thank you for contacting, It seems like you have not setup cron jobs to fetch orders from API Server. you need to setup cron jobs against every methods in `cron.php` controller file.

here is a tutorial about setup cron jobs in codeigniter: https://glennstovall.com/writing-cron-job-in-codeigniter/

**Comment by azouzen** [comment]
great work for unlock web service open source 👍 💯 thanks but there is no confirmation unlock code thanks to add it best luck

**Comment by azouzen** [comment]
http://unlocksotreatall.com   i have use it for my web update cron.php and fix database user duplication  
you fix database by use auto increment

**Comment by muhammad-shariq** [comment]
I have added cron jobs and done PayPal fixes. for further help you can contact with me on my email.
Thanks.

**Comment by imanthaashan77** [comment]
> http://unlocksotreatall.com i have use it for my web update cron.php and fix database user duplication
> you fix database by use auto increment


hello sir , if you are success
can you help me .............    write my whatsapp number    +94712556303   https://wa.me/94712556303

github exclusive web
