### ISSUE TITLE
Unable to import the admin_exclusiveunlock dump:

### ISSUE THREAD

**Issue by ipwnosx** [muhammad-shariq/exclusiveunlock#10]
Unable to import the admin_exclusiveunlock dump:
ERROR 1452 (23000) at line 1269: Cannot add or update a child row: a foreign key constraint fails (`admin_exclusiveunlock`.`#sql-2c6_10d3f`, CONSTRAINT `gsm_member_fileservices_ibfk_1` FOREIGN KEY (`MemberID`) REFERENCES `gsm_members` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE)
Traceback (most recent call last):
File "/opt/psa/admin/sbin/dbbackup", line 6, in <module>
File "/opt/psa/lib/modules/python/dbbackup/dbbackup.py", line 99, in main
restore(options, password)
File "/opt/psa/lib/modules/python/dbbackup/dbbackup.py", line 88, in restore
raise Exception("program 'mysql' finished with non-zero exit code: %d" % p.returncode)
Exception: program 'mysql' finished with non-zero exit code: 1

**Comment by muhammad-shariq** [comment]
please disable foreign key check during import SQL.

**Comment by ipwnosx** [comment]
> please disable foreign key check during import SQL.

man does this still even work, considering its over 3 yrs old and probably deprecated?

**Comment by muhammad-shariq** [comment]
just its still requires php 5.6.

**Comment by imanthaashan77** [comment]
> just its still requires php 5.6.

hello sir , if you are sucess
can you help me .............    write my whatsapp number    +94712556303   https://wa.me/94712556303

**Comment by imanthaashan77** [comment]
> > please disable foreign key check during import SQL.
> 
> man does this still even work, considering its over 3 yrs old and probably deprecated?

hello sir , if you are sucess
can you help me .............    write my whatsapp number    +94712556303   https://wa.me/94712556303
