### ISSUE TITLE
API Not Work

### ISSUE THREAD

**Issue by htetrkarlwin** [muhammad-shariq/exclusiveunlock#12]
I installed this script...in this, dhru fusion api not work ...why ? sir

**Comment by Kurrokage** [comment]
do you have any way to contact you?

**Comment by muhammad-shariq** [comment]
@htetrkarlwin what error are you facing ?

**Comment by imanthaashan77** [comment]
i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303

i setup script , but not work

**Comment by imanthaashan77** [comment]
> I installed this script...in this, dhru fusion api not work ...why ? sir

can i contact you
please write my whastapp    https://wa.me/94712556303                     +94712556303

**Comment by imanthaashan77** [comment]
> do you have any way to contact you?

> I installed this script...in this, dhru fusion api not work ...why ? sir

can i contact you
please write my whastapp    https://wa.me/94712556303                     +94712556303

**Comment by imanthaashan77** [comment]
can i contact you
please write my whastapp https://wa.me/94712556303 +94712556303

**Comment by muhammad-shariq** [comment]
it only support dhuru API 2.0.
