### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by ozonostudio** [muhammad-shariq/exclusiveunlock#13]
After install the script all the front page it's white if I change to development environment return this:

`A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257`

**Comment by imanthaashan77** [comment]
i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303

**Comment by muhammad-shariq** [comment]
You need to downgrade your PHP version to 5.6 so all notices will goes disappeared.
