### ISSUE TITLE
Anyone still using this script?

### ISSUE THREAD

**Issue by tpkfung820** [muhammad-shariq/exclusiveunlock#15]
Hi,

Anyone still using this script? I installed it and imported IMEI services from API Manager. It said record added message successful, but no IMEI services displayed anywhere.

Anyone please advise.

Thanks!

Tony

**Comment by imanthaashan77** [comment]
i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303

**Comment by txorav** [comment]
How to use

**Comment by muhammad-shariq** [comment]
Here is the demo, its working completely but support Dhuru 2.0 API only.

https://demo.gsmworkshop.com/pro/index.php/admin
U: admin@exclusiveunlock.co.uk
P: demo1234

https://demo.gsmworkshop.com/pro/index.php
U: shariq2k@yahoo.com
P: demo1234
