### ISSUE TITLE
Credit api

### ISSUE THREAD

**Issue by rigler86** [muhammad-shariq/exclusiveunlock#16]
Can this be used to make api for credits. I have a tool i want to require credits to use. Also does this script work on newest pho version?

**Comment by macolodalis** [comment]
cannot be u have to build your own one

**Comment by imanthaashan77** [comment]
i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303

**Comment by imanthaashan77** [comment]
> Can this be used to make api for credits. I have a tool i want to require credits to use. Also does this script work on newest pho version?

can i contact you
please write my whastapp https://wa.me/94712556303 +94712556303

**Comment by imanthaashan77** [comment]
> cannot be u have to build your own one

can i contact you
please write my whastapp https://wa.me/94712556303 +94712556303

**Comment by muhammad-shariq** [comment]
Sorry, it did not API did not support logs and credits module.
