### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by giarosenko** [muhammad-shariq/exclusiveunlock#2]
Dear developer,

I found your project quite interesting and want to test and see it. Maybe use it in the future.
I have some issues with installing, I did all the installation parameters at the end my website does not load and show error 500. 

The only problem that I had for sure is the database full name, but I change this at the files. 
I think Apache port also was the problem you were using: 8000 and I needed to change mine to 80
But this did not help too. 

How do I troubleshoot this so I can provide you as much information I can so we can solve it? 

I think the issue is also with the name of the database on my hosting server I can not enter as database name full "exclusiveunlock" due to my username add its like "username_ exclu" company cuts the full name because its big.

**Comment by muhammad-shariq** [comment]
Hello @giarosenko,
if your server is configured on port 80 then you did not need to write port but just the correct URL.

**Comment by giarosenko** [comment]
I have tried to do that, but my server won't load it again. same error 500

**Comment by muhammad-shariq** [comment]
Please open your file `index.php` which you can find on the root of your project and replace line#21 with `define('ENVIRONMENT', 'development');`. This will enable error reporting then send me the actual error.

**Comment by giarosenko** [comment]
After changing to development i got Intenal error on main website. 
Log report says:

```
<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

ERROR - 2018-02-17 12:51:06 --> Severity: Notice  --> Only variable references should be returned by reference /home/imei/public_html/system/core/Common.php 257
ERROR - 2018-02-17 12:53:39 --> Severity: Notice  --> Only variable references should be returned by reference /home/imei/public_html/system/core/Common.php 257
ERROR - 2018-02-17 12:53:44 --> Severity: Notice  --> Only variable references should be returned by reference /home/imei/public_html/system/core/Common.php 257

```

**Comment by muhammad-shariq** [comment]
It seems like a php version issue, Please change your php version to `PHP 5.6`.

**Comment by giarosenko** [comment]
I installed the version of 5.6.33 that is running now, but I can not get any new log report.
The internal error is on the website.

**Comment by muhammad-shariq** [comment]
It seems like, you have disabled error reporting again.

**Comment by imanthaashan77** [comment]
> Dear developer,
> 
> I found your project quite interesting and want to test and see it. Maybe use it in the future.
> I have some issues with installing, I did all the installation parameters at the end my website does not load and show error 500.
> 
> The only problem that I had for sure is the database full name, but I change this at the files.
> I think Apache port also was the problem you were using: 8000 and I needed to change mine to 80
> But this did not help too.
> 
> How do I troubleshoot this so I can provide you as much information I can so we can solve it?
> 
> I think the issue is also with the name of the database on my hosting server I can not enter as database name full "exclusiveunlock" due to my username add its like "username_ exclu" company cuts the full name because its big.


hello sir , if you are success
can you help me .............    write my whatsapp number    +94712556303   https://wa.me/94712556303

github exclusive web
