### ISSUE TITLE
Sql Script 

### ISSUE THREAD

**Issue by majacaem** [muhammad-shariq/exclusiveunlock#20]
Error SQL:

--
-- Constraints for table `gsm_member_fileservices`
--
ALTER TABLE `gsm_member_fileservices`
  ADD CONSTRAINT `gsm_member_fileservices_ibfk_1` FOREIGN KEY (`MemberID`) REFERENCES `gsm_members` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `gsm_member_fileservices_ibfk_2` FOREIGN KEY (`FileServiceID`) REFERENCES `gsm_fileservices` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
MySQL ha dicho: Documentación

#1452 - Cannot add or update a child row: a foreign key constraint fails (`majacaem_exclusiveunlock`.`#sql-2d03b_1b0abf`, CONSTRAINT `gsm_member_fileservices_ibfk_1` FOREIGN KEY (`MemberID`) REFERENCES `gsm_members` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE)

**Comment by imanthaashan77** [comment]
> Error SQL:
> 
> ## --
> -- Constraints for table `gsm_member_fileservices`
> ALTER TABLE `gsm_member_fileservices`
> ADD CONSTRAINT `gsm_member_fileservices_ibfk_1` FOREIGN KEY (`MemberID`) REFERENCES `gsm_members` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
> ADD CONSTRAINT `gsm_member_fileservices_ibfk_2` FOREIGN KEY (`FileServiceID`) REFERENCES `gsm_fileservices` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
> MySQL ha dicho: Documentación
> 
> #1452 - Cannot add or update a child row: a foreign key constraint fails (`majacaem_exclusiveunlock`.`#sql-2d03b_1b0abf`, CONSTRAINT `gsm_member_fileservices_ibfk_1` FOREIGN KEY (`MemberID`) REFERENCES `gsm_members` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE)

can i contact you
please write my whastapp https://wa.me/94712556303 +94712556303

**Comment by muhammad-shariq** [comment]
you should disable foreign key check disable so file will be imported successfully.
