### ISSUE TITLE
Manual reply code dont show code(text replied)

### ISSUE THREAD

**Issue by majacaem** [muhammad-shariq/exclusiveunlock#21]
only direct in phpmyadmin inserting code show it

**Comment by imanthaashan77** [comment]
i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303

**Comment by imanthaashan77** [comment]
> only direct in phpmyadmin inserting code show it

can i contact you
please write my whastapp https://wa.me/94712556303 +94712556303

**Comment by muhammad-shariq** [comment]
attached any screenshot.
