### ISSUE TITLE
Demo pages not active, no support or responses from anyone

### ISSUE THREAD

**Issue by ludmilaunlock** [muhammad-shariq/exclusiveunlock#22]
Seems there is no support so their is no use to develop this script further

These demo pages are not live anymore.

http://www.exclusiveunlock.co.uk/login.html
http://www.exclusiveunlock.co.uk/admin/

**Comment by imanthaashan77** [comment]
i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303

**Comment by muhammad-shariq** [comment]
Yes, demo has been moved to different server.

https://demo.gsmworkshop.com/pro/index.php/admin
U: admin@exclusiveunlock.co.uk
P: demo1234

https://demo.gsmworkshop.com/pro/index.php
U: shariq2k@yahoo.com
P: demo1234
