### ISSUE TITLE
I have the same problem any solution???

### ISSUE THREAD

**Issue by imanthaashan77** [muhammad-shariq/exclusiveunlock#23]
I have the same problem any solution???

_Originally posted by @hsosa88 in https://github.com/muhammad-shariq/exclusiveunlock/issues/11#issuecomment-555811593_

**Comment by imanthaashan77** [comment]
i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303
my script not work , help me

**Comment by muhammad-shariq** [comment]
you need to enable URL rewritting according to your server setup.
