### ISSUE TITLE
Cron jobs not done

### ISSUE THREAD

**Issue by Madol1** [muhammad-shariq/exclusiveunlock#7]
Someone done this script?
I have issue with cron jobs. 
The Cron jobs not past the order to server

**Comment by muhammad-shariq** [comment]
Here are the cron jobs which you needs to be added in your system with php5.6
`
**Cron Jobs**
* * * * * /usr/bin/php56 /<PATH>/index.php cron send_imei_orders

* * * * * /usr/bin/php56 /<PATH>/index.php cron send_file_orders

*/10 * * * * /usr/bin/php56 /<PATH>/index.php cron receive_imei_orders

*/10 * * * * /usr/bin/php56 /<PATH>/index.php cron receive_file_orders`

**Comment by Madol1** [comment]
Must I change the <PATH> with my server path where is the file cron.php stored?
When I only put your cron jobs into server cron jobs nothing happened

**Comment by muhammad-shariq** [comment]
@Madol1 software is build on MVC pattern so you need add cron job with `index.php` and with some parameters.
like:
`/www/index.php cron send_imei_orders`
so you should replace `www` with your software root path where index.php file exists.

**Comment by Madol1** [comment]
Still not working. Can I contact you at whatsup for the help?

**Comment by Madol1** [comment]
Someone can help to get the script working?

**Comment by muhammad-shariq** [comment]
you can also run cron jobs by wget.

`* * * * * /usr/bin/wget http://mydomain.com/cron/send_imei_orders`

`* * * * * /usr/bin/wget http://mydomain.com/cron/send_file_orders`

`*/10 * * * * /usr/bin/wget http://mydomain.com/cron/receive_imei_orders`

`*/10 * * * * /usr/bin/wget http://mydomain.com/cron/receive_file_orders`

**Comment by ederviss** [comment]
IN MY CASE, this is working:

`/usr/local/bin/php /home/MYCPANELUSER/public_html/unlock2/index.php cron send_imei_orders`

PS: Replace _MYCPANELUSER_ with your cpanel user and _unlock2_ is where my installation folder. Delete _unlock2_ if you don`t have subfolder or replace if you have.

**Comment by imanthaashan77** [comment]
> Someone can help to get the script working?

hello sir , if you are sucess
can you help me .............    write my whatsapp number    +94712556303   https://wa.me/94712556303
