### ISSUE TITLE
Add credits error

### ISSUE THREAD

**Issue by ederviss** [muhammad-shariq/exclusiveunlock#8]
Hi there. Awesome work. Can you please tell me why do i have a white (blank) page after i press add found? Should i be redirected to PayPal but i have white page instead with this url: *********/index.php/member/checkout.html
PS: All fields in PayMent Method / Paypal, was filled with my info.
Thank you

**Comment by muhammad-shariq** [comment]
Hello there,
Thank you for contacting. You need to disable test mode if you have saved your live PayPal credentials.

File: https://github.com/muhammad-shariq/exclusiveunlock/blob/master/application/config/constants.php

define('TEST_MODE', FALSE); // FALSE for LIVE transactions
-----Regards,Muhammad Shariq 

    On Saturday, May 4, 2019, 5:59:55 PM GMT+5, ederviss <notifications@github.com> wrote:  
 
 
Hi there. Awesome work. Can you please tell me why do i have a white (blank) page after i press add found? Should i be redirected to PayPal but i have white page instead with this url: *********/index.php/member/checkout.html
PS: All fields in PayMent Method / Paypal, was filled with my info.
Thank you

**Comment by ederviss** [comment]
Yep. Working like a charm. Thank you, again, awesome job.
