### ISSUE TITLE
Warning: Possible phishing attempt detected: The link you used attempted to redirect you to another site.

### ISSUE THREAD

**Issue by ipwnosx** [muhammad-shariq/exclusiveunlock#9]
Warning: Possible phishing attempt detected: The link you used attempted to redirect you to another site.
![Screen Shot 2019-09-17 at 9 36 26 PM](https://user-images.githubusercontent.com/41032246/65105854-92edf900-d993-11e9-9530-54b18b7282c8.png)

**Comment by muhammad-shariq** [comment]
you may be forgot to change the `base_url` in config file `/application/config/config.php`. 

Please change the base_url to your actual domain name.
